insert into turista values ('Matteo', 'Calzetta', 'Pazizo', '1');
insert into proprietario values ('Stellina', 'Architetta', '1', 'Architetta');
insert into proprietario values ('Stirpe', 'Elvira', '1', 'Elvira');
insert into proprietario values ('Moras', 'Filippo', '1', 'Filippo');
insert into proprietario values ('Rossi', 'Graziano', '1', 'Graziano');
insert into proprietario values ('Jankowski', 'Julianski', '1', 'Julianski');
insert into ristorante values ('Uno', 'IndirizzoUno', 'Torino', 'Architetta', '3.1');
insert into ristorante values ('Due', 'IndirizzoDue', 'Torino', 'Architetta', '4.6');
insert into ristorante values ('Tre', 'IndirizzoTre', 'Torino', 'Elvira', '1.6');
insert into ristorante values ('Quattro', 'IndirizzoQuattro', 'Torino', 'Elvira', '4.4');
insert into ristorante values ('Cinque', 'IndirizzoCinque', 'Torino', 'Filippo', '5.0');
insert into ristorante values ('Sei', 'IndirizzoSei', 'Torino', 'Filippo', '2.3');
insert into ristorante values ('Sette', 'IndirizzoSette', 'Torino', 'Graziano', '2.0');
insert into ristorante values ('Otto', 'IndirizzoOtto', 'Torino', 'Graziano', '3.5');
insert into ristorante values ('Nove', 'IndirizzoNove', 'Torino', 'Julianski', '3.9');
insert into ristorante values ('Dieci', 'IndirizzoDieci', 'Torino', 'Julianski', '2.7');
insert into menu values ('Uno', '10.0');
insert into menu values ('Due', '20.0');
insert into menu values ('Tre', '30.0');
insert into menu values ('Quattro', '40.0');
insert into menu values ('Cinque', '50.0');
insert into menu values ('Sei', '60.0');
insert into menu values ('Sette', '70.0');
insert into menu values ('Otto', '80.0');
insert into menu values ('Nove', '90.0');
insert into menu values ('Dieci', '100.0');
insert into piattotipico values ('Pasta');
insert into piatto values ('Uno', 'Pasta', '.', '10.0', '0', '0');
insert into piatto values ('Due', 'Pasta', '.', '20.0', '1', '0');
insert into piatto values ('Tre', 'Pasta', '.', '30.0', '0', '1');
insert into piatto values ('Quattro', 'Pasta', '.', '40.0', '1', '1');
insert into piatto values ('Cinque', 'Pasta', '.', '50.0', '1', '1');
insert into piatto values ('Sei', 'Pasta', '.', '60.0', '0', '0');
insert into piatto values ('Sette', 'Pasta', '.', '70.0', '1', '0');
insert into piatto values ('Otto', 'Pasta', '.', '80.0', '0', '1');
insert into piatto values ('Nove', 'Pasta', '.', '90.0', '1', '1');
insert into piatto values ('Dieci', 'Pasta', '.', '100.0', '1', '1');
insert into apertura values ('Uno', '1', '0', '1');
insert into apertura values ('Uno', '2', '1', '0');
insert into apertura values ('Uno', '3', '1', '1');
insert into apertura values ('Uno', '4', '1', '0');
insert into apertura values ('Uno', '5', '0', '1');
insert into apertura values ('Uno', '6', '0', '1');
insert into apertura values ('Uno', '7', '1', '1');
insert into apertura values ('Due', '1', '1', '1');
insert into apertura values ('Due', '2', '0', '1');
insert into apertura values ('Due', '3', '1', '1');
insert into apertura values ('Due', '4', '0', '1');
insert into apertura values ('Due', '5', '1', '0');
insert into apertura values ('Due', '6', '1', '1');
insert into apertura values ('Due', '7', '0', '0');
insert into apertura values ('Tre', '1', '1', '0');
insert into apertura values ('Tre', '2', '0', '0');
insert into apertura values ('Tre', '3', '1', '0');
insert into apertura values ('Tre', '4', '1', '1');
insert into apertura values ('Tre', '5', '1', '1');
insert into apertura values ('Tre', '6', '1', '1');
insert into apertura values ('Tre', '7', '1', '1');
insert into apertura values ('Quattro', '1', '1', '1');
insert into apertura values ('Quattro', '2', '1', '1');
insert into apertura values ('Quattro', '3', '1', '0');
insert into apertura values ('Quattro', '4', '1', '1');
insert into apertura values ('Quattro', '5', '1', '0');
insert into apertura values ('Quattro', '6', '1', '0');
insert into apertura values ('Quattro', '7', '1', '0');
insert into apertura values ('Cinque', '1', '1', '1');
insert into apertura values ('Cinque', '2', '0', '1');
insert into apertura values ('Cinque', '3', '0', '0');
insert into apertura values ('Cinque', '4', '1', '1');
insert into apertura values ('Cinque', '5', '0', '1');
insert into apertura values ('Cinque', '6', '1', '1');
insert into apertura values ('Cinque', '7', '0', '1');
insert into apertura values ('Sei', '1', '1', '0');
insert into apertura values ('Sei', '2', '1', '1');
insert into apertura values ('Sei', '3', '0', '1');
insert into apertura values ('Sei', '4', '1', '0');
insert into apertura values ('Sei', '5', '1', '1');
insert into apertura values ('Sei', '6', '1', '1');
insert into apertura values ('Sei', '7', '1', '1');
insert into apertura values ('Sette', '1', '0', '1');
insert into apertura values ('Sette', '2', '1', '0');
insert into apertura values ('Sette', '3', '1', '1');
insert into apertura values ('Sette', '4', '1', '1');
insert into apertura values ('Sette', '5', '1', '1');
insert into apertura values ('Sette', '6', '1', '0');
insert into apertura values ('Sette', '7', '1', '1');
insert into apertura values ('Otto', '1', '1', '0');
insert into apertura values ('Otto', '2', '1', '1');
insert into apertura values ('Otto', '3', '1', '1');
insert into apertura values ('Otto', '4', '0', '0');
insert into apertura values ('Otto', '5', '0', '1');
insert into apertura values ('Otto', '6', '0', '1');
insert into apertura values ('Otto', '7', '1', '1');
insert into apertura values ('Nove', '1', '1', '1');
insert into apertura values ('Nove', '2', '1', '1');
insert into apertura values ('Nove', '3', '1', '1');
insert into apertura values ('Nove', '4', '0', '1');
insert into apertura values ('Nove', '5', '1', '1');
insert into apertura values ('Nove', '6', '0', '0');
insert into apertura values ('Nove', '7', '0', '1');
insert into apertura values ('Dieci', '1', '0', '1');
insert into apertura values ('Dieci', '2', '1', '1');
insert into apertura values ('Dieci', '3', '0', '1');
insert into apertura values ('Dieci', '4', '1', '1');
insert into apertura values ('Dieci', '5', '1', '0');
insert into apertura values ('Dieci', '6', '1', '1');
insert into apertura values ('Dieci', '7', '1', '0');